# Generated by Django 4.0.4 on 2022-05-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='url_description',
            new_name='description',
        ),
    ]
